repos:
  # Use pre-commit repo, v4.0.1
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.0.1"
    hooks:
      # Check for files that contain merge conflict strings.
      - id: check-merge-conflict
        stages: [ commit, push ]
      # Trims trailing whitespace.
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
        stages: [ commit ]
      # Checks that scripts with shebangs are executable.
      - id: check-shebang-scripts-are-executable
        stages: [ push ]

    # Use locally installed hooks
  - repo: local

    hooks:
      - id: autoflake
        name: autoflake
        # autoflake is cringe and does not respect .flake8 F401 ignores
        entry: bash -c 'make autoflake_fix filename=$@' --
        language: system
        types: [ python ]
        stages: [ commit ]

      - id: black
        name: black
        entry: poetry
        args:
          - run
          - black
        language: system
        types: [ python ]
        stages: [ commit ]

      - id: isort
        name: isort
        entry: poetry
        args:
          - run
          - isort
        language: system
        types: [ python ]
        stages: [ commit ]

      - id: flake8
        name: flake8
        entry: poetry
        args:
          - run
          - flake8
        language: system
        always_run: true
        pass_filenames: false
        stages: [ push ]
